spring.application.name=AstonIntensiveTas

#PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/userservice
spring.datasource.username=user
spring.datasource.password=password

# JPA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

#Kafka

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


server.port=8080
